### PR TITLE
fixes #3962 travis windows build

### LINKED ISSUE #3962: Travis build for c programs failing due to Windows specific code
**This is a(n):**
- [ ] New algorithm
- [x] Update to an existing algorithm
- [x] Error
- [ ] Proposal to the Repository

**Details:**
* The travis build(as of Job #1944.1) is again failing due to errors from the file code/sorting/src/sleep_sort/sleep_sort.c
* The code is windows specific. Our build system for travis ci targets only the linux os. That's the cause of error

**Proposals:**
* My suggestion is to port the code for sleep sort to play nicely with linux os. I can update the existing algorithm. Then we can add a documentation on how to run c-programs for testing in local system and specifically mention that the current build doesn't support windows specific code.
* Or add a build system config for windows specific files(might cost some time)

@arnavb what do you suggest?

### PR DESCRIPTION
**Pull request by yedhink**
**Fixes issue:**
fixes #3962 

**Changes:**
added linux specific code along with the windows specific code, so as to make it work in both build systems.

### CODE REVIEW

File: code/sorting/src/sleep_sort/sleep_sort.c [hunk 1]
```diff
@@ -1,34 +1,87 @@
...
-    for (i = 0; i < n; i++)
-        threads[i] = (HANDLE)_beginthread(&routine, 0, &arr[i]);
-    WaitForMultipleObjects(n, threads, TRUE, INFINITE);
-    return;
+  int i;
+  HANDLE threads[n];
+  for (i = 0; i < n; i++)
+    threads[i] = (HANDLE)_beginthread(&routine, 0, &arr[i]);
+  WaitForMultipleObjects(n, threads, TRUE, INFINITE);
+  return;
```
Comment (arnavb) [inline code/sorting/src/sleep_sort/sleep_sort.c]:
```suggestion
```

File: code/sorting/src/sleep_sort/sleep_sort.c [hunk 2]
```diff
@@ -1,34 +1,87 @@
...
 {
-    int i;
-    HANDLE threads[n];
-    for (i = 0; i < n; i++)
-        threads[i] = (HANDLE)_beginthread(&routine, 0, &arr[i]);
-    WaitForMultipleObjects(n, threads, TRUE, INFINITE);
-    return;
+  int i;
+  HANDLE threads[n];
+  for (i = 0; i < n; i++)
```
Comment (arnavb) [inline code/sorting/src/sleep_sort/sleep_sort.c]: Pre-increment.

File: code/sorting/src/sleep_sort/sleep_sort.c [hunk 3]
```diff
@@ -1,34 +1,87 @@
...
 
 void sleepSort(int arr[], int n)
 {
-    int i;
-    HANDLE threads[n];
-    for (i = 0; i < n; i++)
-        threads[i] = (HANDLE)_beginthread(&routine, 0, &arr[i]);
-    WaitForMultipleObjects(n, threads, TRUE, INFINITE);
-    return;
+  int i;
```
Comment (arnavb) [inline code/sorting/src/sleep_sort/sleep_sort.c]: Could you move this right above the loop?

File: code/sorting/src/sleep_sort/sleep_sort.c [hunk 4]
```diff
@@ -1,34 +1,87 @@
...
+/* LINUX SPECIFIC CODE*/
+#elif defined(__linux__)
+#include <assert.h>
+#include <stdio.h>
+#include <stdlib.h>
+#include <unistd.h>
+
+static void fdpipe(FILE** readFp, FILE** writeFp)
+{
+  int fds[2], err;
```
Comment (arnavb) [inline code/sorting/src/sleep_sort/sleep_sort.c]: Why is `err` declared here? We use modern C, so just declare it in the middle of the function (i.e `int err = pipe(fds)`).

File: code/sorting/src/sleep_sort/sleep_sort.c [hunk 5]
```diff
@@ -9,19 +9,20 @@
 #include <windows.h>
 void routine(void *a)
```
Comment (arnavb) [inline code/sorting/src/sleep_sort/sleep_sort.c]: Return types go on their own line (style).

Comment (yedhink) [reply code/sorting/src/sleep_sort/sleep_sort.c]: didn't understand what you meant. Can you give an example?

Comment (yedhink) [reply code/sorting/src/sleep_sort/sleep_sort.c]: @arnavb did you mean add function prototypes?

Comment (arnavb) [reply code/sorting/src/sleep_sort/sleep_sort.c]: @yedhink Our [C style guide](https://github.com/OpenGenus/cosmos/tree/master/guides/coding_style/c) mandates that return types go on their own line:

```C
void
function() {
<TAB>...code...
}
```
Make sure to use tabs, not spaces as well.

Comment (yedhink) [reply code/sorting/src/sleep_sort/sleep_sort.c]: @arnavb i thought we were adopting the the linux kernel c style guide as discussed in #3947. I have followed the kernel c style guide. Wont we have to again reformat the code when adopting the new style if we follow the c style guide that you mentioned?

Comment (yedhink) [reply code/sorting/src/sleep_sort/sleep_sort.c]: also i have been developing scripts to autoformat to the linux kernel style guide with the exception of using 4 spaces as mentioned in #3947. So currently changing the code back to the c style you mentioned would be a mess. 

Is it absolutely mandatory to change?

Comment (arnavb) [reply code/sorting/src/sleep_sort/sleep_sort.c]: @yedhink Until the autoformatting script gets merged, please follow our current style guide, because there is no 100% guarantee it will be implemented yet either.

Comment (yedhink) [reply code/sorting/src/sleep_sort/sleep_sort.c]: @arnavb have made the necessary changes. see if its okay.

**Comment by arnavb** [comment]
djldk 2
